sonar.projectKey=Maylon-hub_paperless-ngx
sonar.organization=maylon-hub
sonar.projectName=Paperless-ngx
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/tests/**
sonar.exclusions=src/**/tests/**, src/locale/**, src-ui/**, docs/**, docker/**, scripts/**, .github/**
sonar.language=py
